import type { S3StorageService } from "../storage/s3-storage.service.js";
import type { UserRepository } from "../repositories/user.repository.js";
import type { DocumentRepository } from "../repositories/document.repository.js";
import type { CategoryRepository } from "../repositories/category.repository.js";
import type { CourseRepository } from "../repositories/course.repository.js";
import type { NoteRepository } from "../repositories/note.repository.js";
import type { QuizRepository } from "../repositories/quiz.repository.js";
import type { RoadmapRepository } from "../repositories/roadmap.repository.js";
import type { TaskRepository } from "../repositories/task.repository.js";
import type { UserService } from "../services/user.service.js";
import type { HealthService } from "../services/health.service.js";
import type { JwtService } from "../services/jwt.service.js";
import type { EmailService } from "../services/email.service.js";
import type { AuthService } from "../services/auth.service.js";
import type { DocumentService } from "../services/document.service.js";
import type { NoteService } from "../services/note.service.js";
import type { AiService } from "../services/ai.service.js";
import type { PdfConverterService } from "../services/pdf-converter.service.js";
import type { CategoryService } from "../services/category.service.js";
import type { CourseService } from "../services/course.service.js";
import type { RoadmapService } from "../services/roadmap.service.js";
import type { UserController } from "../api/controllers/user.controller.js";
import type { HealthController } from "../api/controllers/health.controller.js";
import type { AuthController } from "../api/controllers/auth.controller.js";
import type { DocumentController } from "../api/controllers/document.controller.js";
import type { NoteController } from "../api/controllers/note.controller.js";
import type { AiController } from "../api/controllers/ai.controller.js";
import type { CategoryController } from "../api/controllers/category.controller.js";
import type { CourseController } from "../api/controllers/course.controller.js";
import type { RoadmapController } from "../api/controllers/roadmap.controller.js";
import type { AuthMiddleware } from "../middleware/auth.middleware.js";

export interface Cradle {
  s3Storage: S3StorageService;
  userRepository: UserRepository;
  documentRepository: DocumentRepository;
  noteRepository: NoteRepository;
  quizRepository: QuizRepository;
  roadmapRepository: RoadmapRepository;
  taskRepository: TaskRepository;
  categoryRepository: CategoryRepository;
  courseRepository: CourseRepository;
  jwtService: JwtService;
  emailService: EmailService;
  authService: AuthService;
  authMiddleware: AuthMiddleware;
  userService: UserService;
  pdfConverterService: PdfConverterService;
  documentService: DocumentService;
  noteService: NoteService;
  aiService: AiService;
  categoryService: CategoryService;
  courseService: CourseService;
  roadmapService: RoadmapService;
  healthService: HealthService;
  userController: UserController;
  healthController: HealthController;
  authController: AuthController;
  documentController: DocumentController;
  noteController: NoteController;
  aiController: AiController;
  categoryController: CategoryController;
  courseController: CourseController;
  roadmapController: RoadmapController;
}
